"""initial revision

Revision ID: 8a6de93c94ce
Revises: 0e835fdce86a
Create Date: 2025-07-08 12:30:50.404217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6de93c94ce'
down_revision: Union[str, None] = '0e835fdce86a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #пытаюсь переписать первое изменение
    with op.batch_alter_table('services') as bath_op:
        bath_op.drop_constraint(None, 'services', type_='foreignkey')

    #первоначальная версия обновления
    op.drop_constraint(None, 'services', type_='foreignkey')

    #остальные обновления
    op.drop_column('services', 'quantity')
    op.drop_column('services', 'subscription_id')
    op.drop_constraint(None, 'services_availability', type_='foreignkey')
    op.create_foreign_key(None, 'services_availability', 'subscription_services', ['service_id'], ['service_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services_availability', type_='foreignkey')
    op.create_foreign_key(None, 'services_availability', 'services', ['service_id'], ['id'])
    op.add_column('services', sa.Column('subscription_id', sa.INTEGER(), nullable=True))
    op.add_column('services', sa.Column('quantity', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'services', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
